name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 

    - name: Restore dependencies
      run: dotnet restore MyProject.Tests/MyProject.Tests.csproj

    - name: Build
      run: |
       cd MyProject.Tests  
       dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test MyProject.Tests/MyProject.Tests.csproj --configuration Release --no-build
